issues:
  exclude-dirs:
    - e2e

# Run only staticcheck and goimports for now. Additional linters will be enabled one-by-one.
linters:
  enable:
    - errorlint
    - goimports
    - staticcheck
    - sloglint
  disable-all: true

linters-settings:
  goimports:
    local-prefixes: github.com/prometheus/graphite_exporter
